### ISSUE TITLE
Spawn and Fly false positive 

### ISSUE THREAD

**Issue by IamWTbro** [CraftG/Horizon#11]
Please describe the problem in detail and provide as much information as possible.
So whenever you are in fly and then stop flying those 2 checks I mentioned below start spamming and you get kicked. For example, if you fly and then double click space to stop flying you will start glitching in the air and get kicked later. The next false positive is when you /spawn the same thing happens pretty much the 2 checks spam the person with verbose on then kicks you. This also applies to anything that involves "teleporting" such as tpohere, tpa, tpo, etc. When I disable the checks causing this it longer false positive's nor kicks but still causes a bit of lag when you stop flying then you fall.

INFOMATION:
Server: PaperSpigot
Server version: 1.8

bypass/false positive/bug/error/suggestion
ISSUE TYPE: False positive

If reporting a console error.
SERVER LOG: I am not

If reporting a false positive.
HORIZON LOG: Fly Type: Expect
                         Phase Type: Collision
                         Speed Type: Limit
                         Those are the checks false positiving
2019-04-28 11:17:01]Player Camille_106 failed FLY Type:Expect d:-0.09800000190733726, ea:-0.230527368912964, eb:-0.17444000526427114 (+1) Ping:183
[2019-04-28 11:17:01]Player Camille_106 failed PHASE Type:Collision  (+2) Ping:183
[2019-04-28 11:17:01]Player Camille_106 failed FLY Type:Expect d:-0.09800000190733726, ea:-0.30431682745754424, eb:-0.17444000526427114 (+1) Ping:183
[2019-04-28 11:17:01]Player Camille_106 failed PHASE Type:Collision  (+2) Ping:183
[2019-04-28 11:17:02]Player Camille_106 failed FLY Type:Expect d:-0.09800000190733726, ea:-0.37663049823865513, eb:-0.17444000526427114 (+1) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed PHASE Type:Collision  (+2) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed FLY Type:Expect d:-0.09800000190733726, ea:-0.44749789698341763, eb:-0.17444000526427114 (+1) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed PHASE Type:Collision  (+2) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed FLY Type:Expect d:-0.09800000190733726, ea:-0.5169479491049732, eb:-0.17444000526427114 (+1) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed PHASE Type:Collision  (+2) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed FLY Type:Expect d:-0.09800000190733726, ea:-0.5850090015087522, eb:-0.17444000526427114 (+1) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed PHASE Type:Collision  (+2) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed FLY Type:Expect d:-0.09800000190733726, ea:-0.6517088341626173, eb:-0.17444000526427114 (+1) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed PHASE Type:Collision  (+2) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed FLY Type:Expect d:-0.09800000190733726, ea:-0.7170746714356033, eb:-0.17444000526427114 (+1) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed PHASE Type:Collision  (+2) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed FLY Type:Expect d:-0.09800000190733726, ea:-0.7811331932098841, eb:-0.17444000526427114 (+1) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed PHASE Type:Collision  (+2) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed FLY Type:Expect d:-0.09800000190733726, ea:-0.8439105457704985, eb:-0.17444000526427114 (+1) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed PHASE Type:Collision  (+2) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed FLY Type:Expect d:-0.09800000190733726, ea:-0.9054323524772837, eb:-0.17444000526427114 (+1) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed PHASE Type:Collision  (+2) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed FLY Type:Expect d:-0.09800000190733726, ea:-0.9657237242233685, eb:-0.17444000526427114 (+1) Ping:209
[2019-04-28 11:17:02]Player Camille_106 failed PHASE Type:Collision  (+2) Ping:209
[2019-04-28 11:17:03]Player Camille_106 failed FLY Type:Expect d:-0.09800000190733726, ea:-1.0248092696844984, eb:-0.17444000526427114 (+1) Ping:209
[2019-04-28 11:17:03]Player Camille_106 failed PHASE Type:Collision  (+2) Ping:209
[2019-04-28 11:17:03]Player Camille_106 failed FLY Type:Expect d:-0.09800000190733726, ea:-1.082713105363373, eb:-0.17444000526427114 (+1) Ping:209
[2019-04-28 11:17:03]Player Camille_106 failed PHASE Type:Collision  (+2) Ping:209
[2019-04-28 11:17:03]Player Camille_106 failed FLY Type:Expect d:-0.09800000190733726, ea:-1.1394588654330982, eb:-0.17444000526427114 (+1) Ping:209
[2019-04-28 11:17:03]Player Camille_106 failed PHASE Type:Collision  (+2) Ping:209
[2019-04-28 11:17:03]Player Camille_106 failed FLY Type:Expect d:-0.09800000190733726, ea:-1.1950697113837683, eb:-0.17444000526427114 (+1) Ping:209

If reporting a false positive/bypass. (If possible)
VIDEO: Nothing rn

If reporting a bypass.
CLIENT:
Thanks for reading!

**Comment by IamWTbro** [comment]
I can rec a video if needed.

**Comment by CraftG** [comment]
I understand. Thanks for your report, i'm fixing it now.

**Comment by CraftG** [comment]
Fixed. Try the dev build.

**Comment by IamWTbro** [comment]
It works now! Thanks for fixing this! But, there is still 1 problem, when you stop flying you still get glitched for a second or two then fall and if you try to move when falling (after you stop flying) it will put you back where you were when you stopped falling.

**Comment by IamWTbro** [comment]
I actually was able to fix it, for some reason I installed another anticheat to block ghost hand and it's fly check fixed it I guess

**Comment by IamWTbro** [comment]
Never mind, that wasn't the reason. It just stopped glitch on it's own for some reason.

**Comment by IamWTbro** [comment]
I got another false positive though, if you hit someone with a weapon enchanted with knockback they will be teleported back where they started

**Comment by CraftG** [comment]
Thanks, I will fix it.

**Comment by IamWTbro** [comment]
I got another false positive though, if you hit someone with a weapon enchanted with knockback they will be teleported back where they started

**Comment by CraftG** [comment]
Fixed. If you still have problems, you can reopen this issue.
