### ISSUE TITLE
Hacker gets the Debug message

### ISSUE THREAD

**Issue by Polarcrafter2** [CraftG/Horizon#5]
Please describe the problem in detail and provide as much information as possible.

INFOMATION:
Server: Spigot
Server version: 1.12.2

bypass/false positive/bug/error/suggestion
ISSUE TYPE: Hacker gets Debug Message and the op/Owner gets nothing

If reporting a console error.
SERVER LOG: N/A

If reporting a false positive.
HORIZON LOG:
![2019-03-30_16 47 57](https://user-images.githubusercontent.com/49100272/55278363-97522700-530b-11e9-865d-c9e6e6f4bfad.png)

If reporting a false positive/bypass. (If possible)
VIDEO: N/A

If reporting a bypass.
CLIENT: N/A

**Comment by CraftG** [comment]
set 'log.player' in config.yml to false so that players will not be able to see the debug message.

**Comment by Polarcrafter2** [comment]
`# Log system
log:
  # Will Horizon log to file?
  file: true

  # Will Horizon send debug to player?
  player: false

  # Will Horizon send debug to op?
  op: true`

**Comment by Polarcrafter2** [comment]
Not working

**Comment by CraftG** [comment]
try the latest version.

**Comment by CraftG** [comment]
You have not responded, so the problem should have been resolved. If you have other questions, you can reopen it.

**Comment by Polarcrafter2** [comment]
Its not resolved i got a new anticheat, the config of horizon isn't working that was my problem and i had the latest version
